### ISSUE TITLE
tensorrt的支持

### ISSUE THREAD

**Issue by Egrt** [Tau-J/rtmlib#12]
请问能否增加对tensorrt的支持？

**Comment by Egrt** [comment]
`[02/07/2024-21:51:33] [TRT] [E] ModelImporter.cpp:729: --- End node ---
[02/07/2024-21:51:33] [TRT] [E] ModelImporter.cpp:732: ERROR: ModelImporter.cpp:168 In function parseGraph:
[6] Invalid Node - TopK_587
This version of TensorRT only supports input K as an initializer. Try applying constant folding on the model using Polygraphy: https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/cli/surgeon/02_folding_constants
Traceback (most recent call last):
  File "d:/Notebook/rtmlib/rtm.py", line 41, in <module>
    build_model(rtmdet_onnx_model)
  File "d:/Notebook/rtmlib/rtm.py", line 16, in build_model
    build_engine(onnx_file_path, engine_file_path, True)
  File "d:/Notebook/rtmlib/rtm.py", line 28, in build_engine
    raise RuntimeError(f'failed to load ONNX file: {onnx_file_path}')
RuntimeError: failed to load ONNX file: rtmdet_nano_8xb32-300e_hand-267f9c8f.onnx`
我的环境为：
TensorRT 8.5.1.7
当我将onnx模型转换为engine模型时候出现了报错，该如何解决

**Comment by Tau-J** [comment]
Hi @Egrt, RTMPose 的TensorRT转换流程请参考[官方文档](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose)。关于TensorRT推理的支持，在计划之中，但由于版本对齐相对困难，暂时不会在短期内完成

**Comment by chenscottus** [comment]
Please update to TensorRT 8.6.x

**Comment by Egrt** [comment]
> Please update to TensorRT 8.6.x

Thanks, it worked.

**Comment by vieenrose** [comment]
Alternatively, you can enable [TensorrtExecutionProvider](https://oliviajain.github.io/onnxruntime/docs/execution-providers/TensorRT-ExecutionProvider.html#build) on ONNXruntime to use TensorRT as inference backend. Note that you may have to perform [shape inference]() on ONNX model first using [symbolic_shape_infer.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/symbolic_shape_infer.py) to prepare your model. Also for TensorRT 8.2-8.4, [build](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/build_from_source.md) custom TensorRT Ops plug-in from MMdeploy (and load the plug-in to Tensorrt Execution Provider following [usage](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#usage)) is also required.

**Comment by jstumpin** [comment]
@Egrt any reason as for why am I getting only a single object detection at any one time? Using the same code, I'm able to get multiple objects detection. Do note however, I'm using TensorRTv10.x and have made the necessary adjustments as follows:

- https://docs.nvidia.com/deeplearning/tensorrt/latest/api/migration-guide.html
- https://huggingface.co/pesi/rtmo/blob/main/rtmo_gpu.py

Thanks in advance.
